# Generated by Django 3.1 on 2023-12-16 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startingwebsite', '0002_auto_20231216_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tea',
            old_name='Images',
            new_name='image',
        ),
    ]
