# Generated by Django 3.1 on 2023-12-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startingwebsite', '0003_auto_20231216_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='tea',
            name='In_stock',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tea',
            name='Price',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tea',
            name='details',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
