# Generated by Django 3.1 on 2023-12-18 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startingwebsite', '0004_auto_20231217_1418'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rev',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='startingwebsite.tea'),
        ),
        migrations.AddField(
            model_name='rev',
            name='Title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
